#cloud-config
package_update: true
package_upgrade: true
packages:
    - python3-pip
    - build-essential
    - unzip
    - jq
    - git
    - ssh-import-id
users:
  - name: ryan
    groups: [ sudo ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    ssh_authorized_keys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCilMVokeYbySGn4XLfxz2t9NBonRrfMtnEWQZAxwVaKO1fN1xsOjzQ+z2dIfozr2/MRexPS7uE+nezQtJAlvw/sW92O6AKV8hkwdxQojR9UQ6T/5Sd7dWaiuaFcHhNlqAoJaKvx8Y0fA2i+rxdKMPux+mw7SoY+SgH58HNIwGHigAdziFNpGfKms7bzPULI++aPfc0MV3rLdDyWKiejRd87s7MFcJSqkt+KDqSXVozKeF9L9C70ryTAIsBK0eM2y4viqy+NX+4P6MXE8kwBihTtfY1yr9s+0Ypc99/BhuhpZEwQORHQcRaUzNJ41OuemE8+cE5XQcWpzse+GPk7Cv0/+Rkh4H11ogYNjUqHFmjG0/kmwyq39ZNuMIVk5SZl66rgqcdGRJ6yOHBTSFYr68bJmuHOG96U7np/yIW6BZxlxuEuWjko5vYrMlDAzA+/kuuVuhorIe8KXadU56oXWYj4uIynlu9U3KQJBlJxn/FWI4xMooY/VS1Q0l7bHNe49U8DqeFlOKIXCDg4JoShDODDG2+MSmAmqdLnClALBk1ZJC/QeaIsyPzGxjuCObHDGfk/dYwkRIZ2H5DjUDMtnkDQwe8biNtNOlXx15UoiBmOzkfqfFkhekOtC/mzEKMAQUCOBYJbWdMQp0eaHjlUS6nHsojwaPGr6P0g1/DV2pwRw== ryan@dreadnought'
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcsY5IcNEKi6iLe5rfD36yAE6XOi5XxwgZS8q4w6qLsS93/2fgXSvCoxG8LwWZPu6yqHVI8ap2HfzwaG2Wp9vSi5txVbdojVXuOVtUIC6MZnwfNsTpNjTHg7+mksTAHUCNIsIjqRSMCIdhNmTOzKbVMIdaSFsLmH7ITn3+JCtqBlDw9WkHu92W2LNAOcN7QrLS3fUXoLeCEojkl1FiKkhpx8mRlRIo4kq4ZvgOBnvS7+ii/iQiT5vEMKPoA9DJaXV/ZmVWKwfaGUvWHgSKjC+6lDNAwp6YCXOw7rfUvjmS+2H4AhQDGr9zzLHqm1wVQYAhoDsjtOPXOJDrQy71CEIc0kBmceb+zXGqpZHiDkUMIBpiErHKn7pOFoM+GjVtsdsV18DZdEZt6rlHr32Vh9CHt7ieHbueaCZGM1/11cwTlUkhQmApC4xsySvm1f+m0FT6RAoAed7PLek33jy3Q9KnPeu1v5pVhwsGmStGtI9p6A43BgBHtIADvziZEqK4KV0tY5WyBLnBK8JCFURNaOE+a3L1lsYpHFdNkqJK9LRLM6fnJbXF4004Kkcyh33XiC+GfYmF7fUOqXJDR2bEafSDBhU+z0sgCP4BaXA2Fn2zg5tNc5rSxENdTWhjztJ1PUmWIGc5Jf+IWkvjhAMWopTs6Iu9t/4IMLWHQygpKz6G0Q== ryan@andromeda.galaxy'
    ssh_import_id:
      - gh:greyhoundforty
snap:
    commands:
      00: snap install yq
runcmd:
  - ['sh', '-c', 'curl -fsSL https://tailscale.com/install.sh | sh']
  - ['sh', '-c', "echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf && echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf && sudo sysctl -p /etc/sysctl.d/99-tailscale.conf" ]
  - ['tailscale', 'up', '--advertise-routes=10.240.0.0/18', '--authkey={{ tailscale_api_token }}', '--accept-routes']
final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /var/log/cloud-init-output.log'}
